[Patch]
xpui.js_find_8008 = ,(\w+=)56,
xpui.js_repl_8008 = ,${1}32,

[Setting]
overwrite_assets       = 1
check_spicetify_update = 1
prefs_path             = /home/vector/.config/spotify/prefs
current_theme          = catppuccin
color_scheme           = mocha
inject_theme_js        = 1
inject_css             = 1
spotify_path           = /usr/share/spotify/
replace_colors         = 1
spotify_launch_flags   = 
always_enable_devtools = 0

[Preprocesses]
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1
disable_sentry     = 1

[AdditionalOptions]
extensions            = adblock.js
custom_apps           = 
sidebar_config        = 1
home_config           = 1
experimental_features = 1

; DO NOT CHANGE!
[Backup]
version = 1.2.40.599.g606b7f29
with    = 2.36.15
